apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: sttts-bot
spec:
  replicas: 1
  selector:
    deploymentconfig: sttts-bot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deploymentconfig: sttts-bot
        app: sttts-bot
    spec:
      containers:
      - image: sttts-bot:latest
        name: sttts-bot
        env:
        - name: BUGZILLA_URL
          valueFrom:
            secretKeyRef:
              key: BUGZILLA_URL
              name: bugzilla-credentials
        - name: BUGZILLA_LOGIN
          valueFrom:
            secretKeyRef:
              key: BUGZILLA_LOGIN
              name: bugzilla-credentials
        - name: BUGZILLA_PASSWORD
          valueFrom:
            secretKeyRef:
              key: BUGZILLA_PASSWORD
              name: bugzilla-credentials
        - name: BUGZILLA_TOKEN
          valueFrom:
            secretKeyRef:
              key: BUGZILLA_TOKEN
              name: bugzilla-credentials
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              key: SLACK_BOT_TOKEN
              name: slack-token
        - name: SLACK_VERIFICATION_TOKEN
          valueFrom:
            secretKeyRef:
              key: SLACK_VERIFICATION_TOKEN
              name: slack-token
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
              name: podinfo
        volumeMounts:
        - mountPath: "/home"
          name: home
      securityContext:
        fsGroup:
      volumes:
      - name: home
        persistentVolumeClaim:
          claimName: sttts-bot-home
      - name: podinfo
          downwardAPI:
            items:
            - path: "namespace"
              fieldRef:
                fieldPath: metadata.namespace
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - sttts-bot
      from:
        kind: ImageStreamTag
        name: sttts-bot:latest
    type: ImageChange
